/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type SupportingDocument struct {
	// Display name of the document
	DisplayLabel string `json:"displayLabel"`
	// The name of the supporting document field
	FieldName string `json:"fieldName"`
	// Id representing the document
	Id string `json:"id"`
	// Mime-type of the document
	MimeType string `json:"mimeType"`
	// Number of pages in the document
	NumPages int32 `json:"numPages"`
}
