/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

// A JSON  that contains both the id of the newly created agreement and URL / embedded code to direct the user to tne next step in the creation process.
type AgreementCreationResponse struct {
	// The unique identifier of the agreement
	Id string `json:"id"`
}
