/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type DelegatedParticipantSecurityOption struct {
	// The phoneInfo required for the participant to view and sign the document
	PhoneInfo *PhoneInfo `json:"phoneInfo,omitempty"`
}
