/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type ShareCreationInfoList struct {
	// List of ShareCreationInfo
	ShareCreationInfo []ShareCreationInfo `json:"shareCreationInfo"`
}
