/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type AgreementDocuments struct {
	// A list of documents
	Documents []Document `json:"documents"`
	// A list of supporting documents
	SupportingDocuments []SupportingDocument `json:"supportingDocuments,omitempty"`
}
