/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

// A JSON list of all of the fields for a form
type AgreementFormFields struct {
	// List of the form fields in an agreement
	Fields []FormField `json:"fields"`
}
