/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type DelegatedParticipantInfo struct {
	// Email of the participant. In case of modifying a participant set (PUT) this is a required field. In case of GET, this is the required field and will always be returned unless it is a fax workflow (legacy agreements) that were created using fax as input
	Email string `json:"email"`
	// Security options that apply to the participant. This cannot be changed as part of the PUT call
	SecurityOption *DelegatedParticipantSecurityOption `json:"securityOption"`
}
