/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type ShareCreationResponse struct {
	// The email address that was requested
	Email string `json:"email"`
	// The unique identifier of the participant
	ParticipantId string `json:"participantId"`
}
