/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type ShareCreationInfo struct {
	// The email address of the member with whom the agreement will be shared
	Email string `json:"email"`
	// Optional message to the sharee
	Message string `json:"message,omitempty"`
}
