/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type SigningUrlSetInfo struct {
	// The name of the current signer set. Returned only, if the API caller is the sender of agreement
	SigningUrlSetName string `json:"signingUrlSetName,omitempty"`
	// An array of urls for current signer set.
	SigningUrls []SigningUrl `json:"signingUrls"`
}
