/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type SigningUrl struct {
	// The email address of the signer associated with this signing url
	Email string `json:"email"`
	// The email address of the signer associated with this signing url
	EsignUrl string `json:"esignUrl"`
}
