/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type DisplayParticipantSetInfo struct {
	// Displays the info about user set
	DisplayUserSetMemberInfos []DisplayParticipantInfo `json:"displayUserSetMemberInfos"`
	// The name of the display user set. Returned only, if the API caller is the sender of agreement. 
	DisplayUserSetName string `json:"displayUserSetName,omitempty"`
}
