/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type CombinedDocumentPagesInfo struct {
	// List of basic information of all pages of the combined document of an Agreement.
	DocumentPagesInfo []DocumentPageInfo `json:"documentPagesInfo"`
}
