/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type MergefieldInfo struct {
	// The default value of the field
	DefaultValue string `json:"defaultValue"`
	// The name of the field
	FieldName string `json:"fieldName"`
}
