/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type DocumentPageInfo struct {
	// Height of the page
	Height float64 `json:"height"`
	// Index of the page in combined document starting from 1
	Index int32 `json:"index"`
	// Rotation angle of the page in clockwise direction in degree
	Rotation float64 `json:"rotation"`
	// Width of the page
	Width float64 `json:"width"`
}
