/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type ComposeViewConfiguration struct {
	// Controls various file upload options available on the send page
	FileUploadOptions *FileUploadOptions `json:"fileUploadOptions,omitempty"`
	// Should the COMPOSE page be provided with authoring mode selected?
	IsPreviewSelected bool `json:"isPreviewSelected,omitempty"`
}
