/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

// A JSON that contains the id of newly created delegated participant set
type DelegationResponse struct {
	// The unique identifier of the participant set to which the agreement was forwarded.
	Id string `json:"id"`
}
