/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type ParticipantSetInfo struct {
	// The unique label of a participant set.<br>For custom workflows, label specified in the participation set should map it to the participation step in the custom workflow.
	Label string `json:"label,omitempty"`
	// Array of ParticipantInfo objects, containing participant-specific data (e.g. email). All participants in the array belong to the same set
	MemberInfos []ParticipantSetMemberInfo `json:"memberInfos"`
	// Name of the participant set (it can be empty, but needs not to be unique in a single agreement). Maximum no of characters in participant set name is restricted to 255
	Name string `json:"name,omitempty"`
	// Index indicating position at which signing group needs to sign. Signing group to sign at first place is assigned a 1 index. Different signingOrder specified in input should form a valid consecutive increasing sequence of integers. Otherwise signingOrder will be considered invalid. No signingOrder should be specified for SHARE role
	Order int32 `json:"order"`
	// Participant set's private message - all participants in the set will receive the same message
	PrivateMessage string `json:"privateMessage,omitempty"`
	// Role assumed by all participants in the set (signer, approver etc.)
	Role string `json:"role"`
	// When you enable limited document visibility (documentVisibilityEnabled), you can specify which file (fileInfo) should be made visible to which specific participant set.<br>Specify one or more label values of a fileInfos element.<br>Each signer participant sets must contain at least one required signature field in at least one visible file included in this API call; if not a page with a signature field is automatically appended for any missing participant sets. If there is a possibility that one or more participant sets do not have a required signature field in the files included in the API call, all signer participant sets should include a special index value of '0' to make this automatically appended signature page visible to the signer. Not doing so may result in an error. For all other roles, you may omit this value to exclude this page.
	VisiblePages []string `json:"visiblePages,omitempty"`
}
