/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type DelegatedParticipantSetInfo struct {
	// Array of ParticipantInfo objects, containing participant-specific data (e.g. email). All participants in the array belong to the same set
	MemberInfos []DelegatedParticipantInfo `json:"memberInfos"`
	// Participant set's private message - all participants in the set will receive the same message. This cannot be changed as part of the PUT call.
	PrivateMessage string `json:"privateMessage,omitempty"`
}
