/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type PhoneInfo struct {
	// The phone Info country code required for the participant to view and sign the document if authentication method is PHONE
	CountryCode string `json:"countryCode,omitempty"`
	// The phone number required for the participant to view and sign the document if authentication method is PHONE
	Phone string `json:"phone,omitempty"`
}
