/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type AgreementViewInfo struct {
	// Common view configuration for all the available views
	CommonViewConfiguration *CommonViewConfiguration `json:"commonViewConfiguration,omitempty"`
	// Compose page view configuration
	ComposeViewConfiguration *ComposeViewConfiguration `json:"composeViewConfiguration,omitempty"`
	// Name of the requested agreement view
	Name string `json:"name"`
}
