/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

// Location information for form fields
type FormFieldLocation struct {
	// Height of the form field in pixels
	Height float64 `json:"height"`
	// No. of pixels from left of the page for form field placement
	Left float64 `json:"left"`
	// Number of the page where form field has to be placed, starting from 1.
	PageNumber int32 `json:"pageNumber"`
	// No. of pixels from bottom of the page for form field placement
	Top float64 `json:"top"`
	// Width of the form field in pixels
	Width float64 `json:"width"`
}
