/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type SendOptions struct {
	// Control notification mails for agreement completion events - COMPLETED, CANCELLED, EXPIRED and REJECTED
	CompletionEmails string `json:"completionEmails,omitempty"`
	// Control notification mails for agreement-in-process events - DELEGATED, REPLACED
	InFlightEmails string `json:"inFlightEmails,omitempty"`
	// Control notification mails for Agreement initiation events - ACTION_REQUESTED and CREATED
	InitEmails string `json:"initEmails,omitempty"`
}
