/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type VisibilityInfo struct {
	// Specifies the visibility. The possible values are HIDE or SHOW
	Visibility string `json:"visibility"`
}
