/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type DocumentImageUrls struct {
	// ImageSize corresponding to the imageUrl returned 
	ImageSize string `json:"imageSize,omitempty"`
	// A list of image url (one per page).
	ImageURLs []PageImageUrl `json:"imageURLs"`
	// true if images for the associated image size is available, else false.
	ImagesAvailable bool `json:"imagesAvailable,omitempty"`
}
