/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type OfflineDeviceInfo struct {
	// Application Description
	ApplicationDescription string `json:"applicationDescription"`
	// Device Description
	DeviceDescription string `json:"deviceDescription"`
	// The device local time. The device time provided should not be before 30 days of current date.Format should be yyyy-MM-dd'T'HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
	DeviceTime string `json:"deviceTime,omitempty"`
}
