/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type FileUploadOptions struct {
	// Whether library documents link should appear or not. Default value is taken as true
	LibraryDocument bool `json:"libraryDocument,omitempty"`
	// Whether local file upload button should appear or not. Default value is taken as true
	LocalFile bool `json:"localFile,omitempty"`
	// Whether link to attach documents from web sources like Dropbox should appear or not. Default value is taken as true
	WebConnectors bool `json:"webConnectors,omitempty"`
}
