/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

// Hyperlink-specific data for hyperlink form fields
type FormFieldHyperlink struct {
	// Location on the document pointed by the link in case of INTERNAL type link
	DocumentLocation *FormFieldLocation `json:"documentLocation,omitempty"`
	// Type of link in an agreement.
	LinkType string `json:"linkType,omitempty"`
	// URL, in case of EXTERNAL type link
	Url string `json:"url,omitempty"`
}
