/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

// Information required to add or update agreement form fields
type FormFieldPostInfo struct {
	// The ID of the template from which to add new fields
	TemplateId string `json:"templateId"`
}
