/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

// A form field for an agreement.
type FormField struct {
	// Alignment of the text.
	Alignment string `json:"alignment,omitempty"`
	// Who the field is assigned to.  Either a participant set id, null, NOBODY or PREFILL.
	Assignee string `json:"assignee,omitempty"`
	// Background color of the form field in RGB or HEX format
	BackgroundColor string `json:"backgroundColor,omitempty"`
	// Color of the border of the field in RGB or HEX format
	BorderColor string `json:"borderColor,omitempty"`
	// Style of the border of the field.
	BorderStyle string `json:"borderStyle,omitempty"`
	// Width of the border of the field in pixels
	BorderWidth float64 `json:"borderWidth,omitempty"`
	// true if this field's value is calculated from an expression, else false
	Calculated bool `json:"calculated,omitempty"`
	// A predicate (or set of predicates) that determines whether this field is visible and enabled.
	ConditionalAction *FormFieldConditionalAction `json:"conditionalAction,omitempty"`
	// Content Type of the form field.
	ContentType string `json:"contentType,omitempty"`
	// Default value of the form field
	DefaultValue string `json:"defaultValue,omitempty"`
	// Format of the value of the field to be displayed based on the displayFormatType property.
	DisplayFormat string `json:"displayFormat,omitempty"`
	// Format type of the text field.
	DisplayFormatType string `json:"displayFormatType,omitempty"`
	// Display label attached to the field
	DisplayLabel string `json:"displayLabel,omitempty"`
	// Font color of the form field in RGB or HEX format
	FontColor string `json:"fontColor,omitempty"`
	// Font name of the form field
	FontName string `json:"fontName,omitempty"`
	// Font size of the form field in points
	FontSize float64 `json:"fontSize,omitempty"`
	// Text values which are hidden in a drop down form field
	HiddenOptions []string `json:"hiddenOptions,omitempty"`
	// Hyperlink-specific data (e.g. as url, link type)
	Hyperlink *FormFieldHyperlink `json:"hyperlink,omitempty"`
	// Input type of the form field
	InputType string `json:"inputType,omitempty"`
	// All locations in a document where the form field is placed
	Locations []FormFieldLocation `json:"locations"`
	// true if the input entered by the signer has to be masked (like password), false if it shouldn't be
	Masked bool `json:"masked,omitempty"`
	// Text to mask the masked form field
	MaskingText string `json:"maskingText,omitempty"`
	// Maximum length of the input text field in terms of no. of characters
	MaxLength int32 `json:"maxLength,omitempty"`
	// Upper bound of the number that can be entered by the signer
	MaxValue float64 `json:"maxValue,omitempty"`
	// Minimum length of the input text field in terms of no. of characters
	MinLength int32 `json:"minLength,omitempty"`
	// Lower bound of the number that can be entered by the signer
	MinValue float64 `json:"minValue,omitempty"`
	// The name of the form field
	Name string `json:"name"`
	// Origin of Form Field
	Origin string `json:"origin,omitempty"`
	// The type of radio button (if field is radio button, identified by inputType).
	RadioCheckType string `json:"radioCheckType,omitempty"`
	// true if it is a read-only field, else false
	ReadOnly bool `json:"readOnly,omitempty"`
	// true if it is a mandatory field to be filled by the signer, else false
	Required bool `json:"required,omitempty"`
	// Text that appears while hovering over the field
	Tooltip string `json:"tooltip,omitempty"`
	// Rule for validating the field value.
	Validation string `json:"validation,omitempty"`
	// Further data for validating input with regards to the field's specified format. The contents and interpretation of formatData depends on the value of validation.
	ValidationData string `json:"validationData,omitempty"`
	// Error message to be shown to the signer if filled value doesn't match the validations of the form field
	ValidationErrMsg string `json:"validationErrMsg,omitempty"`
	// Expression to calculate value of the form field
	ValueExpression string `json:"valueExpression,omitempty"`
	// If set to false, then the form field is hidden.  Otherwise, it is visible.
	Visible bool `json:"visible,omitempty"`
	// Text values which are visible in a drop down form field
	VisibleOptions []string `json:"visibleOptions,omitempty"`
}
