/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type SenderInfo struct {
	// Company of the sender, if available.
	Company string `json:"company"`
	// Email of the sender of the agreement.
	Email string `json:"email"`
	// Name of the sender, if available.
	Name string `json:"name"`
	//  The unique identifier of the sender of the agreement.
	ParticipantId string `json:"participantId"`
	// True if the sender is the same user that is calling the API.
	Self bool `json:"self"`
	// The agreement status with respect to the participant set. This cannot be changed as part of the PUT call.
	Status string `json:"status"`
}
