/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

type DetailedParticipantSetInfo struct {
	// The unique identifier of the participant set. This cannot be changed as part of the PUT call.
	Id string `json:"id,omitempty"`
	// Array of ParticipantInfo objects, containing participant-specific data (e.g. email). All participants in the array belong to the same set
	MemberInfos []DetailedParticipantInfo `json:"memberInfos"`
	// Name of ParticipantSet (it can be empty, but needs not to be unique in a single agreement). Maximum no of characters in participant set name is restricted to 255. This cannot be changed as part of the PUT call.
	Name string `json:"name,omitempty"`
	// Index indicating sequential signing group (specified for hybrid routing). This cannot be changed as part of the PUT call.
	Order int32 `json:"order"`
	// Participant set's private message - all participants in the set will receive the same message. This cannot be changed as part of the PUT call.
	PrivateMessage string `json:"privateMessage,omitempty"`
	// Role assumed by all participants in the set (signer, approver etc.). This cannot be changed as part of the PUT call.
	Role string `json:"role"`
	// The agreement status with respect to the participant set. This cannot be changed as part of the PUT call.
	Status string `json:"status,omitempty"`
}
