/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

// Conditional actions to perfom on this form field.
type FormFieldConditionalAction struct {
	// Action to show/hide the form field is to be taken on the basis of evaluation of conditions.
	Action string `json:"action,omitempty"`
	// It indicates if any one of the conditions or all of them have to be true.
	AnyOrAll string `json:"anyOrAll,omitempty"`
	// The predicates to be evaluated in order to determine whether this condition is true
	Predicates []FormFieldConditionPredicate `json:"predicates,omitempty"`
}
