/*
 * AdobeSign Aggreements API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package agreements

// Information required to add or replace agreement form fields
type FormFieldPutInfo struct {
	// The list of fields to update or replace. PDF_SIGNATURE inputType field is currently not supported.
	Fields []FormField `json:"fields"`
}
