/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type FileInfo struct {
	// The unique label value of a file info element. In case of custom workflow this will map a file to corresponding file element in workflow definition. This must be specified in case of custom workflow agreement creation request 
	Label string `json:"label,omitempty"`
	// ID for an existing Library document that will be added to the agreement
	LibraryDocumentId string `json:"libraryDocumentId,omitempty"`
	// ID for a transient document that will be added to the agreement
	TransientDocumentId string `json:"transientDocumentId,omitempty"`
	// URL for an external document to add to the agreement
	UrlFileInfo *UrlFileInfo `json:"urlFileInfo,omitempty"`
}
