/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type CommonViewConfiguration struct {
	// Auto LogIn Flag. If true, the URL returned will automatically log the user in. If false, the URL returned will require the credentials. By default its value is false
	AutoLoginUser bool `json:"autoLoginUser,omitempty"`
	// Message template locale
	Locale string `json:"locale,omitempty"`
	// No Chrome Flag. If true, the embedded page is shown without a navigation header or footer. If false, the standard page header and footer will be present. By default its value is false
	NoChrome bool `json:"noChrome,omitempty"`
}
