/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type MegaSigns struct {
	// An array of MegaSign parent agreements
	MegaSignList []MegaSign `json:"megaSignList"`
	// Pagination information for navigating through the response
	Page *PageInfo `json:"page"`
}
