/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type MegaSignChildAgreements struct {
	// A array of MegaSign child agreements
	MegaSignChildAgreementList []MegaSignChildAgreement `json:"megaSignChildAgreementList"`
	// Pagination information for navigating through the response
	Page *PageInfo `json:"page"`
}
