/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

// A JSON  that contains the id of the newly created Mega Sign
type MegaSignCreationResponse struct {
	// Unique identifier of the MegaSign parent agreement
	Id string `json:"id"`
}
