/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type MegaSign struct {
	// The display date for the MegaSign parent agreement. Format would be yyyy-MM-dd'T'HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
	DisplayDate string `json:"displayDate"`
	// True, if the signature type of the MegaSign parent agreement is ESIGN. False, if the signature type of the MegaSign parent agreement is WRITTEN
	Esign bool `json:"esign"`
	// The unique identifier of the MegaSign parent agreement
	Id string `json:"id"`
	// Name of the MegaSign parent agreement
	Name string `json:"name"`
	// Current status of the MegaSign parent agreement from the perspective of the user
	Status string `json:"status"`
}
