/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type MegaSignChildAgreement struct {
	// The display date for the agreement. Format would be yyyy-MM-dd'T'HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
	DisplayDate string `json:"displayDate"`
	// True if this is an e-sign document
	Esign bool `json:"esign"`
	// The unique identifier of the agreement.If provided in POST, it will simply be ignored
	Id string `json:"id,omitempty"`
	// Name of the Agreement
	Name string `json:"name"`
	// This is a server generated attribute which provides the detailed status of an agreement with respect to the apiCaller
	Status string `json:"status,omitempty"`
}
