/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type ChildAgreementsInfo struct {
	// File info containing per child agreement information of megaSign.
	FileInfo *MegaSignChildAgreementsFileInfo `json:"fileInfo"`
}
