/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type VaultingInfo struct {
	// For accounts set up for document vaulting and the option to enable per agreement, this determines whether the document is to be vaulted
	Enabled bool `json:"enabled,omitempty"`
}
