/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type PostSignOption struct {
	// The delay (in seconds) before the user is taken to the success page. If this value is greater than 0, the user will first see the standard Adobe Sign success message, and then after a delay will be redirected to your success page
	RedirectDelay int32 `json:"redirectDelay,omitempty"`
	// A publicly accessible url to which the user will be sent after successfully completing the signing process
	RedirectUrl string `json:"redirectUrl,omitempty"`
}
