/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type MegaSignSecurityOption struct {
	// The authentication method for the participants to have access to view and sign the document.
	ExternalAuthenticationMethod string `json:"externalAuthenticationMethod"`
	// The secondary password that will be used to protect signing the document for internal signers. Note that Adobe Sign will never show this password to anyone, so you will need to separately communicate it to any relevant parties. This password is applied only if password protection is specified for internal signers or all signers
	ExternalPassword string `json:"externalPassword,omitempty"`
	// The authentication method for the participants to have access to view and sign the document.
	InternalAuthenticationMethod string `json:"internalAuthenticationMethod"`
	// The secondary password that will be used to protect signing the document for external signers. Note that Adobe Sign will never show this password to anyone, so you will need to separately communicate it to any relevant parties. This password is applied only if password protection is specified for external signers or all signers
	InternalPassword string `json:"internalPassword,omitempty"`
	// The secondary password that will be used to secure the PDF document. Note that AdobeSign will never show this password to anyone, so you will need to separately communicate it to any relevant parties
	OpenPassword string `json:"openPassword,omitempty"`
}
