/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type MegaSignStateInfo struct {
	// Cancellation information for the agreement. Mandatory while cancelling a megaSign
	MegaSignCancellationInfo *AgreementCancellationInfo `json:"megaSignCancellationInfo,omitempty"`
	// The state to which the megaSign is to be updated. The only valid state for this variable is currently, CANCELLED
	State string `json:"state"`
}
