/*
 * AdobeSign MegaSigns APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package megaSigns

type ExternalId struct {
	// An arbitrary value from your system, which can be specified at sending time and then later returned or queried
	Id string `json:"id,omitempty"`
}
