/*
 * AdobeSign Library Documents APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package libraryDocuments

type LibraryDocument struct {
	// Email address of the library document creator. It will be ignored in POST call
	CreatorEmail string `json:"creatorEmail,omitempty"`
	// True if Library Document is hidden
	Hidden bool `json:"hidden"`
	// The unique identifier that is used to refer to the library template
	Id string `json:"id"`
	// The date on which the library document was last modified. Format would be yyyy-MM-dd'T'HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
	ModifiedDate string `json:"modifiedDate"`
	// The name of the library document
	Name string `json:"name"`
	// Specifies who should have access to this library document. GLOBAL sharing mode is not applicable in POST/PUT calls
	SharingMode string `json:"sharingMode"`
	// Status of the library document
	Status string `json:"status,omitempty"`
	// A list of one or more library template types
	TemplateTypes []string `json:"templateTypes"`
}
