/*
 * AdobeSign Library Documents APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package libraryDocuments

// A JSON object describing the library template
type LibraryDocumentCreationResponse struct {
	// The unique identifier that is used to refer to the library template
	Id string `json:"id"`
}
