/*
 * AdobeSign Library Documents APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package libraryDocuments

type PageImageUrl struct {
	// Page number within the document.
	PageNumber int32 `json:"pageNumber"`
	// An image url.
	Url string `json:"url"`
}
