/*
 * AdobeSign Group URIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package groups

type GroupInfo struct {
	// Unique identifier of the group
	GroupId string `json:"groupId"`
	// Name of the group
	GroupName string `json:"groupName"`
}
