/*
 * AdobeSign Group URIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package groups

type GroupUserInfo struct {
	// The name of company of the user
	Company string `json:"company,omitempty"`
	// The email address of the user
	Email string `json:"email"`
	// The first name of the user
	FirstName string `json:"firstName,omitempty"`
	// A unique identifier of the user resource for REST APIs. This identifier can not be used in SOAP APIs
	Id string `json:"id"`
	// True if user is group admin
	IsGroupAdmin bool `json:"isGroupAdmin"`
	// The last name of the user
	LastName string `json:"lastName,omitempty"`
}
