/*
 * AdobeSign Group URIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package groups

type GroupsInfo struct {
	// The list of groups in the account.
	GroupInfoList []GroupInfo `json:"groupInfoList"`
	// Pagination information for navigating through the response
	Page *PageInfo `json:"page"`
}
