/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type SenderInfo struct {
	// Company of the creator, if available.
	Company string `json:"company"`
	// Email of the creator of the widget.
	Email string `json:"email"`
	// Name of the creator, if available.
	Name string `json:"name"`
	//  The unique identifier of the creator of the widget.
	ParticipantId string `json:"participantId"`
	// True if the creator of the widget is the same user that is calling the API.
	Self bool `json:"self"`
}
