/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type WidgetStateInfo struct {
	// State of the Widget
	State string `json:"state"`
	// Specify custom message which will be displayed  to the user or the URL to which user will be redirected when the widget is accessed in disabled state. This can be specified only in PUT request
	WidgetInActiveInfo *WidgetInActiveInfo `json:"widgetInActiveInfo,omitempty"`
}
