/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type DisplayParticipantInfo struct {
	// Displays the name of the company of the user, if available
	Company string `json:"company,omitempty"`
	// Displays the email of the user
	Email string `json:"email"`
	// Displays the full name of the user, if available. 
	FullName string `json:"fullName,omitempty"`
}
