/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type WidgetInfo struct {
	// List of all the participants in the widget except widget signer
	AdditionalParticipantSetsInfo []WidgetAdditionalParticipationSetInfo `json:"additionalParticipantSetsInfo,omitempty"`
	// URL and associated properties for the error page the widget signer will be taken after failing to authenticate
	AuthFailureInfo *WidgetRedirectionInfo `json:"authFailureInfo,omitempty"`
	// A list of one or more email addresses that you want to copy on this transaction. The email addresses will each receive an email when the final agreement created through widget is signed. The email addresses will also receive a copy of the document, attached as a PDF file
	Ccs []WidgetCcInfo `json:"ccs,omitempty"`
	// URL and associated properties for the success page the widget signer will be taken to after performing desired action on the widget
	CompletionInfo *WidgetRedirectionInfo `json:"completionInfo,omitempty"`
	// Date when widget was created. If provided in POST, it will simply be ignored. Format would be yyyy-MM-dd'T'HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
	CreatedDate string `json:"createdDate,omitempty"`
	// Email of widget creator. Only returned in GET response. Cannot be provided in POST/PUT request. If provided in POST, it will simply be ignored
	CreatorEmail string `json:"creatorEmail,omitempty"`
	// A list of one or more files (or references to files) that will be used to create the widget. If more than one file is provided, they will be combined before the widget is created. Library documents are not permitted. Note: Only one of the four parameters in every FileInfo object must be specified
	FileInfos []FileInfo `json:"fileInfos"`
	// A resource identifier that can be used to uniquely identify the widget in other apis. If provided in POST, it will simply be ignored
	Id string `json:"id,omitempty"`
	// The locale associated with this widget - specifies the language for the signing page and emails, for example en_US or fr_FR. If none specified, defaults to the language configured for the widget creator
	Locale string `json:"locale,omitempty"`
	// The name of the widget that will be used to identify it, in emails, website and other places
	Name string `json:"name"`
	// Secondary security parameters for the widget
	SecurityOption *SecurityOption `json:"securityOption,omitempty"`
	// The state in which the widget should land. For example in order to create a widget in DRAFT state, field should be DRAFT. The state field will never get returned in GET /widgets/{ID} and will be ignored if provided in PUT /widgets/{ID} call. The eventual status of the widget can be obtained from GET /widgets/ID
	State string `json:"state"`
	// Status of the Widget. If provided in POST, it will simply be ignored
	Status string `json:"status,omitempty"`
	// Vaulting properties that allows Adobe Sign to securely store documents with a vault provider
	VaultingInfo *VaultingInfo `json:"vaultingInfo,omitempty"`
	// Represents widget participant for whom email should not be provided
	WidgetParticipantSetInfo *WidgetParticipantSetInfo `json:"widgetParticipantSetInfo"`
}
