/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

// A JSON object describing the widget
type WidgetCreationResponse struct {
	// The unique identifier of widget which can be used to retrieve the data entered by the signers.
	Id string `json:"id"`
}
