/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type WidgetEventDeviceLocation struct {
	// Latitude coordinate
	Latitude float32 `json:"latitude"`
	// Longitude coordinate
	Longitude float32 `json:"longitude"`
}
