/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type DetailedWidgetParticipantSetInfo struct {
	// The unique identifier of the participant set. This cannot be changed as part of the PUT call.
	Id string `json:"id,omitempty"`
	// Array of ParticipantInfo objects, containing participant-specific data (e.g. email). All participants in the array belong to the same set
	MemberInfos []DetailedParticipantInfo `json:"memberInfos"`
	// Index indicating sequential signing group (specified for hybrid routing). This cannot be changed as part of the PUT call.
	Order int32 `json:"order"`
	// Role assumed by all participants in the set (signer, approver etc.). This cannot be changed as part of the PUT call.
	Role string `json:"role"`
}
