/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type UserWidget struct {
	// True if agreement is hidden for the user
	Hidden bool `json:"hidden"`
	// The unique identifier of a widget
	Id string `json:"id"`
	// The embedded javascript code of the widget
	Javascript string `json:"javascript"`
	// The date on which the widget was last modified. Format would be yyyy-MM-dd'T'HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
	ModifiedDate string `json:"modifiedDate"`
	// The name of the widget.
	Name string `json:"name"`
	// The widget status (AUTHORING, ACTIVE, DRAFT, DISABLED)
	Status string `json:"status"`
	// The hosted url of the widget
	Url string `json:"url"`
}
