/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type DigitalSignatureInfo struct {
	// Company name captured during digital signing
	Company string `json:"company"`
	// Email captured during digital signing
	Email string `json:"email"`
	// Name captured during digital signing
	Name string `json:"name"`
}
