/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type WidgetView struct {
	// Embedded code of url of resource 
	EmbeddedCode string `json:"embeddedCode,omitempty"`
	// Expiration of user url 
	Expiration string `json:"expiration,omitempty"`
	// True if this view is the current view
	IsCurrent bool `json:"isCurrent"`
	// Name of the requested widget view
	Name string `json:"name"`
	// Url of resource location
	Url string `json:"url,omitempty"`
}
