/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type DisplayWidgetParticipantSetInfo struct {
	// Displays the info about user set
	DisplayUserSetMemberInfos []DisplayParticipantInfo `json:"displayUserSetMemberInfos"`
}
