/*
 * AdobeSign Widgets APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package widgets

type WidgetMembersInfo struct {
	// Information about the widget additional participant Sets
	AdditionalParticipantSets []DetailedWidgetParticipantSetInfo `json:"additionalParticipantSets,omitempty"`
	// Information of CC participants of the widget.
	CcsInfo []CcParticipantInfo `json:"ccsInfo"`
	// Information of the creator of the widget.
	CreatorInfo *SenderInfo `json:"creatorInfo"`
	// Information of the participants with whom the widget has been shared.
	SharesInfo []ShareParticipantInfo `json:"sharesInfo"`
	// Information about the widget participant Set
	WidgetParticipantSet *DetailedWidgetParticipantSetInfo `json:"widgetParticipantSet,omitempty"`
}
