/*
 * AdobeSign Users APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package users

type UserStateInfo struct {
	// An optional comment describing why you want to activate/deactivate a given user
	Comment string `json:"comment,omitempty"`
	// The state to which the user is to be updated. The valid states for this variable is currently, ACTIVE and INACTIVE
	State string `json:"state"`
}
