/*
 * AdobeSign Users APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package users

type UserInfo struct {
	// The name of company of the user
	Company string `json:"company,omitempty"`
	// The email address of the user
	Email string `json:"email"`
	// The first name of the user
	FirstName string `json:"firstName,omitempty"`
	// A unique identifier of the user resource for REST APIs as issued by Sign.
	Id string `json:"id"`
	// True if user is account admin
	IsAccountAdmin bool `json:"isAccountAdmin"`
	// The last name of the user
	LastName string `json:"lastName,omitempty"`
}
