/*
 * AdobeSign Users APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package users

type UserStatusUpdateResponse struct {
	// The result of the attempt to activate or deactivate the user
	Code string `json:"code"`
	// String result message if there was no error
	Message string `json:"message,omitempty"`
	// A status value showing the result of this operation
	State string `json:"state"`
}
