/*
 * AdobeSign Users APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package users

type DetailedUserInfo struct {
	// Type of account to which the user belongs (null if no account)
	AccountType string `json:"accountType,omitempty"`
	// The name of company of the user
	Company string `json:"company,omitempty"`
	// The email address of the user
	Email string `json:"email"`
	// The first name of the user
	FirstName string `json:"firstName,omitempty"`
	// A unique identifier of the user resource for REST APIs as issued by Sign.
	Id string `json:"id"`
	// The initials of the user
	Initials string `json:"initials,omitempty"`
	// True if the user is account admin
	IsAccountAdmin bool `json:"isAccountAdmin"`
	// The last name of the user
	LastName string `json:"lastName,omitempty"`
	// The UI locale of the user
	Locale string `json:"locale,omitempty"`
	// The phone number of the user
	Phone string `json:"phone,omitempty"`
	// Status of the user
	Status string `json:"status"`
	// The job title of the user
	Title string `json:"title,omitempty"`
}
