/*
 * AdobeSign Users APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package users

type UserGroupInfo struct {
	// Unique identifier of the group
	Id string `json:"id"`
	// True if user is group admin.
	IsGroupAdmin bool `json:"isGroupAdmin"`
	// Name of the group. This will be ignored as part of PUT call.
	Name string `json:"name,omitempty"`
}
