/*
 * AdobeSign WebHooks APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package webhooks

type WebhookMegaSignEvents struct {
	// Determines whether megaign detailed info will be returned in the response payload
	IncludeDetailedInfo bool `json:"includeDetailedInfo,omitempty"`
}
