/*
 * AdobeSign WebHooks APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package webhooks

type WebhookConditionalParams struct {
	// Conditional parameters for webhook agreement events
	WebhookAgreementEvents *WebhookAgreementEvents `json:"webhookAgreementEvents,omitempty"`
	// Conditional parameters for webhook megasign events
	WebhookMegaSignEvents *WebhookMegaSignEvents `json:"webhookMegaSignEvents,omitempty"`
	// Conditional parameters for webhook widget events
	WebhookWidgetEvents *WebhookWidgetEvents `json:"webhookWidgetEvents,omitempty"`
}
