/*
 * AdobeSign WebHooks APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package webhooks

// A JSON  that contains the id of the newly created webhook
type WebhookCreationResponse struct {
	// An identifier of the webhook resource created
	Id string `json:"id,omitempty"`
}
