/*
 * AdobeSign WebHooks APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package webhooks

type WebhookWidgetEvents struct {
	// Determines whether agreement detailed info will be returned in the response payload
	IncludeDetailedInfo bool `json:"includeDetailedInfo,omitempty"`
	// Determines whether document info will be returned in the response payload
	IncludeDocumentsInfo bool `json:"includeDocumentsInfo,omitempty"`
	// Determines whether participants info will be returned in the response payload
	IncludeParticipantsInfo bool `json:"includeParticipantsInfo,omitempty"`
}
