/*
 * AdobeSign WebHooks APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package webhooks

type WebhookAgreementEvents struct {
	// Determines whether agreement detailed info will be returned in the response payload
	IncludeDetailedInfo bool `json:"includeDetailedInfo,omitempty"`
	// Determines whether document info will be returned in the response payload
	IncludeDocumentsInfo bool `json:"includeDocumentsInfo,omitempty"`
	// Determines whether participants info will be returned in the response payload
	IncludeParticipantsInfo bool `json:"includeParticipantsInfo,omitempty"`
	// Determines whether documents will be returned in webhook response payload. If set to true, signed document will be returned in base 64 encoded format in JSON when signing is complete
	IncludeSignedDocuments bool `json:"includeSignedDocuments,omitempty"`
}
